### ISSUE TITLE
hibernate lazy initialization collection, session was closed

### ISSUE THREAD

**Issue by rmageshkumar-greytip** [memcached/memcached#1107]
Problem:

We are using memcache session backup manager to store the session in the tomcat. We are using kryotranscoderfactory or kryo lib as serializer lib. 

As we are using the spring security, it is saving the security_context in the session. Our Security_context object contains multiple params like user,authorities, credentials etc.

After authorization , while trying to fetch the session from memcache session manager, it is failing due to the below error.

de.javakaffee.web.msm.TranscoderDeserializationException: com.esotericsoftware.kryo.KryoException: org.hibernate.LazyInitializationException: failed to lazily initialize a collection, no session or session was closed
Serialization trace:
features (com.magesh.common.model.user.Role)
role (com.magesh.common.model.user.RoleFeature)
roleFeatures (com.magesh.common.model.user.AcegiRoleSet)
roleSet (com.magesh.model.user.EdbNamedUser)
user (com.magesh.common.model.AuthenticatedUser)
principal (org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken)
authentication (org.springframework.security.core.context.SecurityContextImpl)
at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.deserializeAttributes(KryoTranscoder.java:213)
at de.javakaffee.web.msm.TranscoderService.deserializeAttributes(TranscoderService.java:167)
at de.javakaffee.web.msm.TranscoderService.deserialize(TranscoderService.java:124)
at de.javakaffee.web.msm.MemcachedSessionService.loadFromMemcached(MemcachedSessionService.java:1155)
at de.javakaffee.web.msm.MemcachedSessionService.findSession(MemcachedSessionService.java:605)
at de.javakaffee.web.msm.MemcachedBackupSessionManager.findSession(MemcachedBackupSessionManager.java:201)
at org.apache.catalina.connector.Request.doGetSession(Request.java:2932)
at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2677)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:451

Our AcegiRoleset class like below.

AcegiRoleset/ Roleset.java

private Set<Role> roles;
private Map<String, RoleFeature> roleFeatures;
private String accessRights;

Userr.java

private Integer employee;
private String userName;	
private String password;
private String email;
@Optional("com.magesh.common.model.user.User.roles")
private Set<Role> roles;
@Optional("com.magesh.common.model.user.User.roleSet")
private RoleSet roleSet;

when it  is trying to deserialize the AuthenticatedUser object, it is failing and throwing the hibernate session closed error.

Library versions:

JDK Version: 1.8
Kryo Version: 3.x
tomcat version: tomcat9
memcache session manager : 2.3
msm kryo serializer : 1.9.7
kryoserializer: 0.37 and other dependencies.

Please  help me to solve this issue.

**Comment by dormando** [comment]
Sorry, you need to ask this question in a tomcat support forum.
