### ISSUE TITLE
memcached error 21

### ISSUE THREAD

**Issue by myworking82** [memcached/memcached#114]
I am using in my Debian 8.2:
memcached                      1.4.21-1.1
libmemcached11:amd64           1.0.18-4
pylibmc==1.5.0

and got this errors:

 'shallow': False,
 'url_rule': <Rule '/' (HEAD, POST, OPTIONS, GET) -> index_page.index>,
 'view_args': {}}
Traceback (most recent call last):
  File "/srv/venv/project/local/lib/python2.7/site-packages/flask_cache/__init__.py", line 540, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "/srv/venv/project/local/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 399, in set
    return self._client.set(key, value, timeout)
Error: error 21 from memcached_set: SUCCESS

what it is meen and how i can fix it?

**Comment by dormando** [comment]
You should talk to the pylibmc author. that's not a very intuitive error, but doesn't have much to do with the daemon, sorry.
