### ISSUE TITLE
ConcurrentModificationException Memcached multithreading

### ISSUE THREAD

**Issue by santoshsgithub** [memcached/memcached#167]
I am getting java.util.ConcurrentModificationException when I am using Memcached for setting & getting value from multiple thread concurrently.

java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
        at java.util.HashMap$EntryIterator.next(HashMap.java:934)
        at java.util.HashMap$EntryIterator.next(HashMap.java:932)
        at java.util.HashMap.writeObject(HashMap.java:1098)
        at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:975)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1480)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1416)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1528)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1493)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1416)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
        at com.danga.MemCached.MemCachedClient.set(MemCachedClient.java:763)
        at com.danga.MemCached.MemCachedClient.set(MemCachedClient.java:542)
        at com.cacheengine.MemoryCacheUtil.addToMemCacheWithExpiryDate(MemoryCacheUtil.java:79)

Please refer link for more details - http://stackoverflow.com/questions/37905851/concurrentmodificationexception-memcached-set-get-from-multithreading

Could you please advise on this issue

**Comment by dormando** [comment]
Hi,

unfortunately this is the issue tracker for the memcached daemon. You seem to have a problem in using one of the clients. I'd recommend stopping by the mailing list if stackoverflow doesn't help (https://groups.google.com/forum/#!forum/memcached). At a glance, it looks like your client isn't built to do what you're doing. There are other java clients which are more meant to be used by multiple threads (spymemcached).

going to close this.
