### ISSUE TITLE
About executing extstore exception exit

### ISSUE THREAD

**Issue by zer0e** [memcached/memcached#779]
Hello, when I fuzzed the memcached, I found that the `stats extstore` command will cause memcached exited abnormally.   
When I compild with AddressSanitizer(ASan), I print out these error.      
    
```
ASAN:DEADLYSIGNAL
=================================================================
==52177==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000a0 (pc 0x7f3d9f2effd0 bp 0x7f3d9affcee0 sp 0x7f3d9affce88 T2)
==52177==The signal is caused by a READ memory access.
==52177==Hint: address points to the zero page.
    #0 0x7f3d9f2effcf in __pthread_mutex_lock_full (/lib/x86_64-linux-gnu/libpthread.so.0+0x9fcf)
    #1 0x5602e0b55eeb in extstore_get_stats /home/zer0e/memcached/memcached-1.6.9/extstore.c:160
    #2 0x5602e0b5e25d in process_extstore_stats /home/zer0e /memcached/memcached-1.6.9/storage.c:72
    #3 0x5602e0b4555c in process_stat /home/zer0e/memcached/memcached-1.6.9/proto_text.c:718
    #4 0x5602e0b4ae10 in process_command /home/zer0e/memcached/memcached-1.6.9/proto_text.c:2628
    #5 0x5602e0b4cfe3 in try_read_command_ascii /home/zer0e/memcached/memcached-1.6.9/proto_text.c:409
    #6 0x5602e0b036a7 in try_read_command_negotiate /home/zer0e/memcached/memcached-1.6.9/memcached.c:2249
    #7 0x5602e0b0c699 in drive_machine /home/zer0e/memcached/memcached-1.6.9/memcached.c:3014
    #8 0x5602e0b0e0d9 in event_handler /home/zer0e/memcached/memcached-1.6.9/memcached.c:3291
    #9 0x7f3d9f5238f7  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1e8f7)
    #10 0x7f3d9f52433e in event_base_loop (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1f33e)
    #11 0x5602e0b2b1e0 in worker_libevent /home/zer0e/memcached/memcached-1.6.9/thread.c:481
    #12 0x7f3d9f2ed6da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #13 0x7f3d9f01671e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12171e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libpthread.so.0+0x9fcf) in __pthread_mutex_lock_full
Thread T2 created by T0 here:
    #0 0x7f3d9f78dd2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x5602e0b2fa65 in create_worker /home/zer0e/memcached/memcached-1.6.9/thread.c:369
    #2 0x5602e0b2fa65 in memcached_thread_init /home/zer0e/memcached/memcached-1.6.9/thread.c:1012
    #3 0x5602e0b1877a in main /home/zer0e/memcached/memcached-1.6.9/memcached.c:5741
    #4 0x7f3d9ef16bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

==52177==ABORTING
```  

When I read the document, I know `extstore` is on by default after version 1.6, but need to work with `-o ext_path=/path/to/a/ datafile:5G`  startup options.   
I think maybe should deal with this mistake more friendly, Instead of quit by mistake?  
Thanks.

**Comment by dormando** [comment]
Yup, bug, whoops. thanks! Think I got another report for this as well but I'm behind on maintenance, sorry.

**Comment by zer0e** [comment]
@dormando Oh, glad to get your reply. I read the source code of memcached. I think the code should be added at line 718 of proto_text.c to prevent the program from crashing and exiting. 

```
else if (strcmp(subcommand, "extstore") == 0) {
    if (ext_storage == NULL) {
        out_string(c, "SERVER_ERROR storage file not specified");
        return;
    }
    process_extstore_stats(&append_stats, c);
```
What do you think of this code change?   
Thanks.

**Comment by dormando** [comment]
Yes, thanks. This is a simple change but I'm in the middle of some larger changes at the moment. I'll get to this as soon as I can.

**Comment by zer0e** [comment]
That's wonderful! Wish you all the best!

**Comment by dormando** [comment]
This took way too long to get to, sorry. It's queued up for the next release.

**Comment by dormando** [comment]
Out in 1.6.10

**Comment by zyingp** [comment]
Fixed in commit https://github.com/memcached/memcached/commit/6512edb22e326acdf8267b4d3c0b88fe707bb86f
