### ISSUE TITLE
Alignment issues on SPARC

### ISSUE THREAD

**Issue by matoro** [memcached/memcached#902]
**Describe the bug**
SPARC support is currently broken due to alignment issues.

* Debian build tracker:  https://buildd.debian.org/status/logs.php?pkg=memcached&arch=sparc64
* Gentoo bug:  https://bugs.gentoo.org/636552

**System Information**
 - Version of memcached:  Most recently tested is 1.6.15
 - Hardware detail:  Test machine is an Oracle SPARC T4-1

**Detail (please include!)**
The patches below address the first couple failures:

```
diff --git a/murmur3_hash.c b/murmur3_hash.c
index 9c3edf3..b89314c 100644
--- a/murmur3_hash.c
+++ b/murmur3_hash.c
@@ -47,7 +47,9 @@ static inline uint32_t rotl32 ( uint32_t x, int8_t r )
 
 static FORCE_INLINE uint32_t getblock32 ( const uint32_t * p, int i )
 {
-  return p[i];
+  uint32_t tmp_buf = 0;
+  memcpy(&tmp_buf, ((uint8_t*)p) + i * sizeof(uint32_t) / sizeof(uint8_t), sizeof(uint32_t) / sizeof(uint8_t));
+  return tmp_buf;
 }
 
 //-----------------------------------------------------------------------------
diff --git a/murmur3_hash.h b/murmur3_hash.h
index e2820e1..b34a0b0 100644
--- a/murmur3_hash.h
+++ b/murmur3_hash.h
@@ -9,6 +9,7 @@
 // Platform-specific functions and macros
 #include <stdint.h>
 #include <stddef.h>
+#include <string.h>
 
 //-----------------------------------------------------------------------------
 ```
 
 ```
 diff --git a/memcached.h b/memcached.h
index 3435677..0a265b2 100644
--- a/memcached.h
+++ b/memcached.h
@@ -161,7 +161,7 @@
 /** Item client flag conversion */
 #define FLAGS_CONV(it, flag) { \
     if ((it)->it_flags & ITEM_CFLAGS) { \
-        flag = *((uint32_t *)ITEM_suffix((it))); \
+        memcpy(&flag, ITEM_suffix(it), sizeof(uint32_t)); \
     } else { \
         flag = 0; \
     } \
```

```
diff --git a/storage.c b/storage.c
index 890437e..ceefc18 100644
--- a/storage.c
+++ b/storage.c
@@ -543,7 +543,7 @@ static int storage_write(void *storage, const int clsid, const int item_age) {
                 buf_it->it_flags &= ~ITEM_LINKED;
                 buf_it->exptime = crc32c(0, (char*)io.buf+STORE_OFFSET, orig_ntotal-STORE_OFFSET);
                 extstore_write(storage, &io);
-                item_hdr *hdr = (item_hdr *) ITEM_data(hdr_it);
+                item_hdr *hdr = (item_hdr *) ITEM_schunk(hdr_it);
                 hdr->page_version = io.page_version;
                 hdr->page_id = io.page_id;
                 hdr->offset  = io.offset;
```

Unfortunately, I'm unsure how to solve the next problem, which also occurs in `binary-extstore.t`:

```
#0  0x00000100000c7984 in storage_write (storage=0x1000021d180, clsid=25, item_age=2) at storage.c:518
518                     buf_it->time = it_info.hv;
[Current thread is 1 (Thread 0xfff800010e823840 (LWP 62492))]
(gdb) bt full
#0  0x00000100000c7984 in storage_write (storage=0x1000021d180, clsid=25, item_age=2) at storage.c:518
        buf_it = 0xfff8000101c3cff9
        hdr = 0xfff800010ae59bf8
        bucket = 0
        hdr_it = 0xfff800010ae59b50
        did_moves = 0
        it_info = {it = 0xfff800010ad1bfd0, hv = 629284634}
        io = {data = 0x100000c8720 <storage_write_thread+1264>, next = 0xfff8000124000b70, buf = 0xfff8000101c3cff9 "", iov = 0x0, iovcnt = 0, 
          page_version = 1, len = 20069, offset = 180612, page_id = 1, mode = OBJ_IO_WRITE, cb = 0x6}
        it = 0xfff800010ad1bfd0
        orig_ntotal = 20069
        flags = 19
        __PRETTY_FUNCTION__ = "storage_write"
#1  0x00000100000c8844 in storage_write_thread (arg=0x1000021d180) at storage.c:624
        chunks_free = 16
        did_move = true
        mem_limit_reached = true
        item_age = 2
        target = 0
        x = 25
        min_class = 9
        do_sleep = false
        storage = 0x1000021d180
        backoff = {0, 0, 0, 0, 0, 0, 0, 0, 0, 2 <repeats 16 times>, 1 <repeats 39 times>}
        counter = 58
        to_sleep = 390
        l = 0xfff8000124000b70
```

Some notes from Discord:

![maim_1655145864](https://user-images.githubusercontent.com/12038583/173423131-d6fa0857-3c63-4e9b-9429-5ceefb5d790c.png)

**Comment by dormando** [comment]
Wonder if forcing NEED_ALIGN would deal with this? There're another couple issues in which the NEED_ALIGN check (which was originally written for SPARC!) is failing to fire.

That said murmurhash should've worked just fine, and did back when I had sparc hosts.

@matoro - dunno if you still care, but: https://github.com/memcached/memcached/issues/1220#issuecomment-2770251664 - wonder what the compile/test error log looks like if this workaround is applied.

**Comment by glaubitz** [comment]
If anyone needs a machine for testing on SPARC, please check out the [GCC Compile Farm](https://gcc.gnu.org/wiki/CompileFarm) which provides free access to such machines for testing.
